version: "3.3"
services:
  java:
    build: ./java
    container_name: java-container
    ports:
      - 8080:8080
    tty: true
  db:
    build: ./db
    container_name: db-container
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
  adminer:
    image: adminer
    container_name: adminer-container
    restart: always
    ports:
      - 8081:8080
