version: "3"
services:
  db:
    build: ./db
    container_name: db-container
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
    ports:
      - 3306:3306
  adminer:
    image: adminer
    container_name: adminer-container
    restart: always
    ports:
      - 8081:8080
